/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Center, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useSpring, animated } from '@react-spring/three';
import { angleToRadians } from '@/utils/angle';

export default function Keyboard(props) {
  // const group = useRef();
  const { nodes, materials } = useGLTF(
    'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/mechanical-keyboard/model.gltf'
  );

  return (
    <Center {...props}>
      <group dispose={null}>
        <mesh geometry={nodes.Case.geometry} material={nodes.Case.material} />
        <mesh
          geometry={nodes.Keyboard_cable.geometry}
          material={nodes.Keyboard_cable.material}
        />
        <mesh
          geometry={nodes.Keycaps.geometry}
          material={materials['Keycap material']}
        />
      </group>
    </Center>
  );
}

useGLTF.preload(
  'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/mechanical-keyboard/model.gltf'
);
