'use client';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense } from 'react';
import {
  Center,
  PerspectiveCamera,
  PresentationControls,
  useGLTF,
} from '@react-three/drei';
import { useSpring, animated, useScroll } from '@react-spring/three';

import { angleToRadians } from '@/utils/angle';
import { Canvas } from '@react-three/fiber';
import Lights from './background/Lights';
import LoadScreen from '../LoadScreen';
import { Leptop } from './Models/Leptop';

export function LeptopScene(props) {
  // scroll position
  const { scrollYProgress } = useScroll();
  // camera positon
  const { cameraPosition } = useSpring({
    from: { cameraPosition: [0, 0, 30] },
    to: {
      cameraPosition: scrollYProgress.to((v) => {
        const position = 30 - v * 20;
        return [0, 0, position];
      }),
    },
  });
  // animations
  const randomFloat = (min, max) => Math.random() * (max - min) + min;
  const randomRotation = () => [
    angleToRadians(randomFloat(-10, 10)),
    angleToRadians(randomFloat(-10, 10)),
    angleToRadians(randomFloat(-10, 10)),
  ];

  //
  const [settings, api] = useSpring(() => ({
    loop: true,
    from: {
      position: [0, 0, 0],
      rotation: [angleToRadians(0), angleToRadians(0), angleToRadians(0)],
    },
    to: [
      {
        position: [
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
        ],
        rotation: randomRotation(),
      },
      {
        position: [
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
        ],
        rotation: randomRotation(),
      },
      {
        position: [
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
        ],
        rotation: randomRotation(),
      },
      {
        position: [
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
          randomFloat(-0.5, 0.5),
        ],
        rotation: randomRotation(),
      },
      {
        position: [0, 0, 0],
        rotation: [angleToRadians(0), angleToRadians(0), angleToRadians(0)],
      },
    ],
    config: { duration: randomFloat(20000, 15000) },
  }));

  return (
    <div {...props}>
      <Suspense fallback={<LoadScreen />}>
        <Canvas>
          <animated.mesh position={cameraPosition}>
            <PerspectiveCamera makeDefault />
          </animated.mesh>
          <Lights />
          <animated.mesh {...settings} dispose={null}>
            <PresentationControls snap={true}>
              <Center position={[0, -0.5, 0]}>
                <Leptop
                  scale={0.0052}
                  rotation={[
                    angleToRadians(40),
                    angleToRadians(20),
                    angleToRadians(0),
                  ]}
                />
              </Center>
            </PresentationControls>
          </animated.mesh>
        </Canvas>
      </Suspense>
    </div>
  );
}
