import React from 'react';
import ShopPage from '../components/shop/ShopPage';

export const metadata = {
  title: 'Shop | Dor Plaur | Web Dev',
  description: 'Generated by create next app',
};

const Shop = () => {
  return <ShopPage />;
};

export default Shop;
