import Script from 'next/script';
import Navbar from '../components/nav/Navbar';
import styles from '@/styles/Dashboard.module.css';

export const metadata = {
  title: 'Dashboard | Dor Plaur | Web Dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // alerts

  // get data for hero title

  return (
    <>
      <Script
        async
        src="https://upload-widget.cloudinary.com/global/all.js"
        type="text/javascript"
      />

      <div className={styles.nav}>
        <Navbar dashborad />
      </div>
      {children}
    </>
  );
}
